### ISSUE TITLE
latest tests.coffee failing ... any suggestion for fix?

### ISSUE THREAD

**Issue by cmcc** [pstaender/mongraph#5]
Philipp,
Just updated to your latest version of Mongraph (0.1.15), but am hitting this problem when performing 'npm run test'. Do you know what might be causing this. I'm not sure if it's related to my earlier attempt to 'npm update' to the latest Mongraph, which appeared to fail (see screenshot below). Instead, I ended up using git pull to get the latest Mongraph.

Any thoughts you might have on fixing this would be greatly appreciated.

Thanks,
Colum

 #dataForNode()
        ✓ expect to get null by default (99ms)
        ✓ expect to get attributes for index 
        ✓ expect to delete values in document and on node (107ms)
        ◦ expect to get node with indexed fields from mongoose schema: 
/home/parallels/node_modules/mongraph/test/tests.coffee:698
                expect(result[0].data['my_id']).to.be.equal value
               ^
TypeError: Cannot read property 'data' of undefined
    at Request._callback (/home/parallels/node_modules/mongraph/test/tests.coffee:698:16)
    at Request.self.callback (/home/parallels/node_modules/request/index.js:148:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/home/parallels/node_modules/request/index.js:876:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/parallels/node_modules/request/index.js:827:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:883:14
    at process._tickCallback (node.js:415:13)

> mongraph@0.1.16 clean /home/parallels/node_modules/mongraph
> find src test -name '*.js' -delete -o -name '*.map' -delete

![unknown](https://f.cloud.github.com/assets/1991179/604943/9d000970-cd05-11e2-986a-6cd03f31a295.png)

**Comment by pstaender** [comment]
@gabrielmancini , I updated the tests and they are running fine with Neo4j v2 -  v2.1 (and newer mongodb). Since older version(s) won't be supported anyway, I'll close the issue. I hope you're OK with that.
